before_script:
 - apt-get update -qq

build-minimal:
 script:
 - apt-get install -y -qq cmake libsdl2-dev tidy
 - rm -rf /usr/include/zlib.h /usr/include/png.h /usr/include/readline*
 - ./configure --disable-small-mem --disable-dsp --enable-debug
               --disable-tracing --enable-werror
 - make
 - make test

build-32bit:
 script:
 - dpkg --add-architecture i386
 - apt-get update -qq
 - apt-get install -y cmake clang gcc-multilib libgcc1:i386 libportmidi-dev:i386
                      libpng-dev:i386 libglib2.0-dev:i386 zlib1g-dev:i386
                      libsdl2-dev:i386 libudev-dev:i386 libreadline-dev:i386
 - CC="clang" CFLAGS="-m32 -O3 -Werror" ./configure --enable-debug
 - make
 - file src/hatari | grep 32.bit
 - make test

build-mingw:
 image: fedora:latest
 before_script:
 - dnf update -y
 - dnf install -y cmake make gcc mingw32-gcc mingw32-SDL2 mingw32-zlib
 script:
 - cmake -DCMAKE_TOOLCHAIN_FILE=cmake/Toolchain-mingw32-win64_32.cmake
         -DENABLE_WERROR:BOOL=1 .
 - make
